[tool.poetry]
name = "bank-marketing"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
mlflow = "^2.18.0"
bayesian-optimization = "^2.0.0"
statsmodels = "^0.14.4"
ipykernel = "^6.29.5"
seaborn = "^0.13.2"
lightgbm = "^4.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
